CREATE TABLE IF NOT EXISTS blogs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  xml_url TEXT NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  blog_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL UNIQUE,
  -- utc epoch
  published_at INTEGER,
  favorite BOOL,
  read BOOL,
  FOREIGN KEY (blog_id) REFERENCES blogs(id)
);

CREATE TABLE IF NOT EXISTS feeds (
  blog_id INTEGER PRIMARY KEY,
  hash TEXT NOT NULL,
  etag TEXT,
  last_modified TEXT NOT NULL,
  FOREIGN KEY (blog_id) REFERENCES blogs(id)
) WITHOUT ROWID;
