name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Setup Flyctl (fly.io)
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install dependencies
        run: uv sync --locked

      - name: "Validate - Test Suite"
        run: uv run pytest

      - name: "Validate - Lints"
        run: uv run ruff check

      - name: "Validate - Formatting"
        run: uv run ruff format --check

      - name: "Validate - Types"
        run: uv run pytest

      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
